/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-04-05 10:51:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class climsRecords_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/housys/FingerprintClient_IDSL_DEVICEFIX03042026/FingerprintClient_IDSL_DEVICEFIX/app/tomcat/webapps/demo/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1771481672000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>CLIMSVIEW records</title>\n");

    pageContext.setAttribute("APP_PATH", request.getContextPath());
    pageContext.setAttribute("deviceSn", request.getParameter("deviceSn"));

      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery-1.12.4.min.js\"></script>\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/bootstrap-3.3.7-dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-12\">\n");
      out.write("                <h1>CLIMSVIEW Records</h1>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row\" style=\"margin-bottom: 10px;\">\n");
      out.write("            <div class=\"col-md-12\">\n");
      out.write("                <button class=\"btn btn-default\" id=\"back_log_btn\">Back To LogRecords</button>\n");
      out.write("                <button class=\"btn btn-primary\" id=\"refresh_btn\">Refresh</button>\n");
      out.write("                <span id=\"source_info\" style=\"display:none;\"></span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row\" style=\"margin-bottom: 10px;\">\n");
      out.write("            <div class=\"col-md-12\">\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"climsSearchInputTop\"\n");
      out.write("                    placeholder=\"Search by User ID / Name\" style=\"width: 320px; display:inline-block;\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-12\">\n");
      out.write("                <table class=\"table table-hover table-striped\" id=\"clims_table\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>#</th>\n");
      out.write("                            <th>DeviceLogId</th>\n");
      out.write("                            <th>DownloadDate</th>\n");
      out.write("                            <th>ProjectId</th>\n");
      out.write("                            <th>UserId</th>\n");
      out.write("                            <th>Name</th>\n");
      out.write("                            <th>LogDate</th>\n");
      out.write("                            <th>Direction</th>\n");
      out.write("                            <th>DeviceSerial</th>\n");
      out.write("                            <th>DeviceId</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6\" id=\"page_info_area\"></div>\n");
      out.write("            <div class=\"col-md-4 col-md-offset-2\" id=\"page_nav_area\"></div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        var totalRecord, currentPage;\n");
      out.write("        var currentDeviceSn = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${deviceSn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("        var currentClimsSearchKeyword = \"\";\n");
      out.write("        var climsSearchDebounceTimer = null;\n");
      out.write("        var climsAllRecords = [];\n");
      out.write("        var climsFilteredRecords = [];\n");
      out.write("        var climsPageSize = 8;\n");
      out.write("        var climsSourceMeta = {\n");
      out.write("            source: \"\",\n");
      out.write("            deviceSn: \"\",\n");
      out.write("            mappingMissing: false\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        function normalizeClimsSearchText(value) {\n");
      out.write("            return $.trim((value || \"\"));\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function queueClimsSearchReload() {\n");
      out.write("            if (climsSearchDebounceTimer) {\n");
      out.write("                clearTimeout(climsSearchDebounceTimer);\n");
      out.write("            }\n");
      out.write("            climsSearchDebounceTimer = setTimeout(function() {\n");
      out.write("                applyClimsFilterAndRender(true);\n");
      out.write("            }, 220);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function buildNavigatePageNums(pageNum, pages) {\n");
      out.write("            var nums = [];\n");
      out.write("            if (pages <= 0) {\n");
      out.write("                return nums;\n");
      out.write("            }\n");
      out.write("            var navSize = 5;\n");
      out.write("            var start = pageNum - Math.floor(navSize / 2);\n");
      out.write("            var end = start + navSize - 1;\n");
      out.write("            if (start < 1) {\n");
      out.write("                start = 1;\n");
      out.write("                end = Math.min(pages, navSize);\n");
      out.write("            }\n");
      out.write("            if (end > pages) {\n");
      out.write("                end = pages;\n");
      out.write("                start = Math.max(1, end - navSize + 1);\n");
      out.write("            }\n");
      out.write("            for (var i = start; i <= end; i++) {\n");
      out.write("                nums.push(i);\n");
      out.write("            }\n");
      out.write("            return nums;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function buildClimsPageResult(pn) {\n");
      out.write("            var total = climsFilteredRecords.length;\n");
      out.write("            var pages = total === 0 ? 1 : Math.ceil(total / climsPageSize);\n");
      out.write("            var safePageNum = pn;\n");
      out.write("            if (!safePageNum || safePageNum < 1) {\n");
      out.write("                safePageNum = 1;\n");
      out.write("            }\n");
      out.write("            if (safePageNum > pages) {\n");
      out.write("                safePageNum = pages;\n");
      out.write("            }\n");
      out.write("            var startIndex = (safePageNum - 1) * climsPageSize;\n");
      out.write("            var endIndex = Math.min(startIndex + climsPageSize, total);\n");
      out.write("            var list = climsFilteredRecords.slice(startIndex, endIndex);\n");
      out.write("            var startRow = total === 0 ? 0 : startIndex + 1;\n");
      out.write("            return {\n");
      out.write("                extend: {\n");
      out.write("                    pageInfo: {\n");
      out.write("                        list: list,\n");
      out.write("                        pageNum: safePageNum,\n");
      out.write("                        pages: pages,\n");
      out.write("                        total: total,\n");
      out.write("                        startRow: startRow,\n");
      out.write("                        hasPreviousPage: safePageNum > 1,\n");
      out.write("                        hasNextPage: safePageNum < pages,\n");
      out.write("                        navigatepageNums: buildNavigatePageNums(safePageNum, pages)\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            };\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function applyClimsFilterAndRender(resetToFirstPage) {\n");
      out.write("            var keyword = normalizeClimsSearchText(currentClimsSearchKeyword).toLowerCase();\n");
      out.write("            if (keyword === \"\") {\n");
      out.write("                climsFilteredRecords = climsAllRecords.slice(0);\n");
      out.write("            } else {\n");
      out.write("                climsFilteredRecords = $.grep(climsAllRecords, function(item) {\n");
      out.write("                    var userIdText = normalizeClimsSearchText(item ? item.userId : \"\").toLowerCase();\n");
      out.write("                    var userNameText = normalizeClimsSearchText(item ? item.userName : \"\").toLowerCase();\n");
      out.write("                    return userIdText.indexOf(keyword) !== -1 || userNameText.indexOf(keyword) !== -1;\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("            if (resetToFirstPage) {\n");
      out.write("                currentPage = 1;\n");
      out.write("            }\n");
      out.write("            to_page(currentPage || 1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function loadClimsRecordsData() {\n");
      out.write("            var payload = { fetchAll: true };\n");
      out.write("            if (currentDeviceSn && currentDeviceSn.length > 0) {\n");
      out.write("                payload.deviceSn = currentDeviceSn;\n");
      out.write("            }\n");
      out.write("            $.ajax({\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/climsRecords\",\n");
      out.write("                data: payload,\n");
      out.write("                type: \"GET\",\n");
      out.write("                success: function(result) {\n");
      out.write("                    var ext = result && result.extend ? result.extend : {};\n");
      out.write("                    var pageInfo = ext.pageInfo ? ext.pageInfo : null;\n");
      out.write("                    climsAllRecords = pageInfo && pageInfo.list ? pageInfo.list : [];\n");
      out.write("                    climsSourceMeta = {\n");
      out.write("                        source: ext.source ? ext.source : \"\",\n");
      out.write("                        deviceSn: ext.deviceSn ? ext.deviceSn : \"\",\n");
      out.write("                        mappingMissing: ext.mappingMissing ? true : false\n");
      out.write("                    };\n");
      out.write("                    applyClimsFilterAndRender(true);\n");
      out.write("                },\n");
      out.write("                error: function() {\n");
      out.write("                    climsAllRecords = [];\n");
      out.write("                    climsSourceMeta = { source: \"\", deviceSn: currentDeviceSn, mappingMissing: false };\n");
      out.write("                    applyClimsFilterAndRender(true);\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        $(function() {\n");
      out.write("            loadClimsRecordsData();\n");
      out.write("            $(\"#climsSearchInputTop\").on(\"input\", function() {\n");
      out.write("                currentClimsSearchKeyword = normalizeClimsSearchText($(this).val());\n");
      out.write("                queueClimsSearchReload();\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $(\"#refresh_btn\").click(function() {\n");
      out.write("            loadClimsRecordsData();\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $(\"#back_log_btn\").click(function() {\n");
      out.write("            window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logRecords.jsp?deviceSn=\" + currentDeviceSn;\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        function to_page(pn) {\n");
      out.write("            if (climsSearchDebounceTimer) {\n");
      out.write("                clearTimeout(climsSearchDebounceTimer);\n");
      out.write("                climsSearchDebounceTimer = null;\n");
      out.write("            }\n");
      out.write("            var result = buildClimsPageResult(pn);\n");
      out.write("            build_table(result);\n");
      out.write("            build_page_info(result);\n");
      out.write("            build_page_nav(result);\n");
      out.write("            build_source_info();\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function build_source_info() {\n");
      out.write("            $(\"#source_info\").text(\"\");\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function build_table(result) {\n");
      out.write("            $(\"#clims_table tbody\").empty();\n");
      out.write("            var rows = result.extend.pageInfo.list;\n");
      out.write("            var i = result.extend.pageInfo.startRow;\n");
      out.write("            $.each(rows, function(index, item) {\n");
      out.write("                $(\"<tr></tr>\")\n");
      out.write("                    .append($(\"<td></td>\").append(i++))\n");
      out.write("                    .append($(\"<td></td>\").append(item.deviceLogId))\n");
      out.write("                    .append($(\"<td></td>\").append(item.downloadDate))\n");
      out.write("                    .append($(\"<td></td>\").append(item.projectId))\n");
      out.write("                    .append($(\"<td></td>\").append(item.userId))\n");
      out.write("                    .append($(\"<td></td>\").append(item.userName ? item.userName : \"-\"))\n");
      out.write("                    .append($(\"<td></td>\").append(item.logDate))\n");
      out.write("                    .append($(\"<td></td>\").append(item.direction))\n");
      out.write("                    .append($(\"<td></td>\").append(item.deviceSerialNum ? item.deviceSerialNum : \"-\"))\n");
      out.write("                    .append($(\"<td></td>\").append(item.deviceId))\n");
      out.write("                    .appendTo(\"#clims_table tbody\");\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function build_page_info(result) {\n");
      out.write("            $(\"#page_info_area\").empty();\n");
      out.write("            $(\"#page_info_area\").append(\n");
      out.write("                \"Current_Page:\" + result.extend.pageInfo.pageNum +\n");
      out.write("                \", Count_Page :\" + result.extend.pageInfo.pages +\n");
      out.write("                \", All_Records:\" + result.extend.pageInfo.total\n");
      out.write("            );\n");
      out.write("            totalRecord = result.extend.pageInfo.pages;\n");
      out.write("            currentPage = result.extend.pageInfo.pageNum;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function build_page_nav(result) {\n");
      out.write("            $(\"#page_nav_area\").empty();\n");
      out.write("            var ul = $(\"<ul></ul>\").addClass(\"pagination\");\n");
      out.write("            var firstPageLink = $(\"<a></a>\").append(\"first\").attr(\"href\", \"javascript:void(0);\");\n");
      out.write("            var prePageLink = $(\"<a></a>\").append(\"&laquo;\").attr(\"href\", \"javascript:void(0);\");\n");
      out.write("            var firstPageLi = $(\"<li></li>\").append(firstPageLink);\n");
      out.write("            var prePageLi = $(\"<li></li>\").append(prePageLink);\n");
      out.write("\n");
      out.write("            if (!result.extend.pageInfo.hasPreviousPage) {\n");
      out.write("                firstPageLi.addClass(\"disabled\");\n");
      out.write("                prePageLi.addClass(\"disabled\");\n");
      out.write("            } else {\n");
      out.write("                firstPageLink.on(\"click\", function(e) {\n");
      out.write("                    e.preventDefault();\n");
      out.write("                    to_page(1);\n");
      out.write("                });\n");
      out.write("                prePageLink.on(\"click\", function(e) {\n");
      out.write("                    e.preventDefault();\n");
      out.write("                    to_page(result.extend.pageInfo.pageNum - 1);\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("            ul.append(firstPageLi).append(prePageLi);\n");
      out.write("\n");
      out.write("            $.each(result.extend.pageInfo.navigatepageNums, function(index, item) {\n");
      out.write("                var numLink = $(\"<a></a>\").append(item).attr(\"href\", \"javascript:void(0);\");\n");
      out.write("                var numLi = $(\"<li></li>\").append(numLink);\n");
      out.write("                if (result.extend.pageInfo.pageNum == item) {\n");
      out.write("                    numLi.addClass(\"active\");\n");
      out.write("                }\n");
      out.write("                numLink.on(\"click\", function(e) {\n");
      out.write("                    e.preventDefault();\n");
      out.write("                    to_page(item);\n");
      out.write("                });\n");
      out.write("                ul.append(numLi);\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            var nextPageLink = $(\"<a></a>\").append(\"&raquo;\").attr(\"href\", \"javascript:void(0);\");\n");
      out.write("            var lastPageLink = $(\"<a></a>\").append(\"last\").attr(\"href\", \"javascript:void(0);\");\n");
      out.write("            var nextPageLi = $(\"<li></li>\").append(nextPageLink);\n");
      out.write("            var lastPageLi = $(\"<li></li>\").append(lastPageLink);\n");
      out.write("            if (!result.extend.pageInfo.hasNextPage) {\n");
      out.write("                nextPageLi.addClass(\"disabled\");\n");
      out.write("                lastPageLi.addClass(\"disabled\");\n");
      out.write("            } else {\n");
      out.write("                nextPageLink.on(\"click\", function(e) {\n");
      out.write("                    e.preventDefault();\n");
      out.write("                    to_page(result.extend.pageInfo.pageNum + 1);\n");
      out.write("                });\n");
      out.write("                lastPageLink.on(\"click\", function(e) {\n");
      out.write("                    e.preventDefault();\n");
      out.write("                    to_page(result.extend.pageInfo.pages);\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("            ul.append(nextPageLi).append(lastPageLi);\n");
      out.write("\n");
      out.write("            var navEle = $(\"<nav></nav>\").append(ul);\n");
      out.write("            navEle.appendTo(\"#page_nav_area\");\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
