/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-04-05 10:51:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class schedulerStatus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/housys/FingerprintClient_IDSL_DEVICEFIX03042026/FingerprintClient_IDSL_DEVICEFIX/app/tomcat/webapps/demo/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1771481672000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Scheduler Daily Status</title>\n");

    pageContext.setAttribute("APP_PATH", request.getContextPath());

      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery-1.12.4.min.js\"></script>\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/bootstrap-3.3.7-dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("    .status-pill {\n");
      out.write("        display: inline-block;\n");
      out.write("        padding: 3px 8px;\n");
      out.write("        border-radius: 12px;\n");
      out.write("        color: #fff;\n");
      out.write("        font-size: 11px;\n");
      out.write("        font-weight: 600;\n");
      out.write("        letter-spacing: 0.3px;\n");
      out.write("    }\n");
      out.write("    .status-success { background: #2e7d32; }\n");
      out.write("    .status-failed { background: #c62828; }\n");
      out.write("    .status-partial { background: #ef6c00; }\n");
      out.write("    .status-running { background: #1565c0; }\n");
      out.write("    .status-not-run { background: #616161; }\n");
      out.write("    .status-unknown { background: #546e7a; }\n");
      out.write("    .sync-summary-box {\n");
      out.write("        margin-top: 8px;\n");
      out.write("        margin-bottom: 8px;\n");
      out.write("        padding: 8px 10px;\n");
      out.write("        border: 1px solid #d9e2ec;\n");
      out.write("        border-radius: 4px;\n");
      out.write("        background: #f8fbff;\n");
      out.write("        font-size: 12px;\n");
      out.write("        line-height: 1.5;\n");
      out.write("        word-break: break-word;\n");
      out.write("    }\n");
      out.write("    .sync-section-title {\n");
      out.write("        margin-top: 8px;\n");
      out.write("        margin-bottom: 8px;\n");
      out.write("        font-weight: 700;\n");
      out.write("    }\n");
      out.write("    .view-toggle-wrap {\n");
      out.write("        margin-left: 12px;\n");
      out.write("    }\n");
      out.write("    .view-toggle-wrap .btn {\n");
      out.write("        min-width: 150px;\n");
      out.write("    }\n");
      out.write("    .status-view {\n");
      out.write("        display: none;\n");
      out.write("    }\n");
      out.write("    .status-view.active {\n");
      out.write("        display: block;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("    <div class=\"row\" style=\"margin-top: 12px;\">\n");
      out.write("        <div class=\"col-md-12\">\n");
      out.write("            <h2>Scheduler Daily Status</h2>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"row\" style=\"margin-bottom: 10px;\">\n");
      out.write("        <div class=\"col-md-12\">\n");
      out.write("            <button class=\"btn btn-default\" id=\"back_btn\">Back To Home</button>\n");
      out.write("            <button class=\"btn btn-primary\" id=\"refresh_btn\">Refresh</button>\n");
      out.write("            <div class=\"btn-group view-toggle-wrap\" role=\"group\">\n");
      out.write("                <button class=\"btn btn-info\" id=\"show_per_device_btn\">Per Device Status</button>\n");
      out.write("                <button class=\"btn btn-default\" id=\"show_scheduled_btn\">Scheduled Status</button>\n");
      out.write("            </div>\n");
      out.write("            <span id=\"status_msg\" style=\"margin-left: 12px; color: #337ab7;\"></span>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"view_per_device\" class=\"status-view\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-12\">\n");
      out.write("                <h4 class=\"sync-section-title\">SetUserToAllDevice Per Device Status</h4>\n");
      out.write("                <div id=\"db_sync_summary\" class=\"sync-summary-box\">Loading sync status...</div>\n");
      out.write("                <table class=\"table table-hover table-striped table-bordered\" id=\"db_sync_device_table\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>#</th>\n");
      out.write("                            <th>Device</th>\n");
      out.write("                            <th>Online</th>\n");
      out.write("                            <th>Last Status</th>\n");
      out.write("                            <th>Last Sync At</th>\n");
      out.write("                            <th>Last Queued</th>\n");
      out.write("                            <th>Delivered</th>\n");
      out.write("                            <th>Pending</th>\n");
      out.write("                            <th>Queued Users</th>\n");
      out.write("                            <th>Queued This Run</th>\n");
      out.write("                            <th>ETA(sec)</th>\n");
      out.write("                            <th>Message</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody></tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"view_scheduled\" class=\"status-view\">\n");
      out.write("        <div class=\"row\" style=\"margin-bottom: 10px;\">\n");
      out.write("            <div class=\"col-md-12\">\n");
      out.write("                <label style=\"font-weight: normal;\">\n");
      out.write("                    Last\n");
      out.write("                    <select id=\"days_select\" class=\"form-control\" style=\"display:inline-block; width:90px; height:30px;\">\n");
      out.write("                        <option value=\"7\">7 Days</option>\n");
      out.write("                        <option value=\"15\">15 Days</option>\n");
      out.write("                        <option value=\"30\" selected=\"selected\">30 Days</option>\n");
      out.write("                        <option value=\"60\">60 Days</option>\n");
      out.write("                    </select>\n");
      out.write("                </label>\n");
      out.write("                <label style=\"margin-left: 12px; font-weight: normal;\">\n");
      out.write("                    Page Size\n");
      out.write("                    <select id=\"page_size_select\" class=\"form-control\" style=\"display:inline-block; width:90px; height:30px;\">\n");
      out.write("                        <option value=\"10\" selected=\"selected\">10</option>\n");
      out.write("                        <option value=\"20\">20</option>\n");
      out.write("                        <option value=\"30\">30</option>\n");
      out.write("                        <option value=\"50\">50</option>\n");
      out.write("                    </select>\n");
      out.write("                </label>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row\" style=\"margin-bottom: 8px;\">\n");
      out.write("            <div class=\"col-md-12\" id=\"summary_area\"></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-12\">\n");
      out.write("                <table class=\"table table-hover table-striped\" id=\"scheduler_table\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>#</th>\n");
      out.write("                            <th>Date</th>\n");
      out.write("                            <th>Daily Status</th>\n");
      out.write("                            <th>Run Count</th>\n");
      out.write("                            <th>Success</th>\n");
      out.write("                            <th>Failed</th>\n");
      out.write("                            <th>First Start</th>\n");
      out.write("                            <th>Last Finish</th>\n");
      out.write("                            <th>Enabled Users</th>\n");
      out.write("                            <th>Disabled Users</th>\n");
      out.write("                            <th>Deleted Users</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody></tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row\" style=\"margin-bottom: 12px;\">\n");
      out.write("            <div class=\"col-md-12 text-right\" id=\"pagination_area\"></div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    var currentPage = 1;\n");
      out.write("    var currentView = \"perDevice\";\n");
      out.write("    var schedulerLoadedOnce = false;\n");
      out.write("\n");
      out.write("    function toInt(value, fallback) {\n");
      out.write("        var n = parseInt(value, 10);\n");
      out.write("        if (isNaN(n)) {\n");
      out.write("            return (typeof fallback === \"number\") ? fallback : 0;\n");
      out.write("        }\n");
      out.write("        return n;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function safeText(value) {\n");
      out.write("        if (value === null || value === undefined || value === \"\") {\n");
      out.write("            return \"-\";\n");
      out.write("        }\n");
      out.write("        return value;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function safeUpper(value) {\n");
      out.write("        return $.trim((value || \"\")).toUpperCase();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function safeMessage(value) {\n");
      out.write("        var text = $.trim(value || \"\");\n");
      out.write("        if (text === \"\") {\n");
      out.write("            return \"-\";\n");
      out.write("        }\n");
      out.write("        if (text.length > 120) {\n");
      out.write("            return text.substring(0, 120) + \"...\";\n");
      out.write("        }\n");
      out.write("        return text;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function statusClass(status) {\n");
      out.write("        if (status === \"SUCCESS\") { return \"status-success\"; }\n");
      out.write("        if (status === \"FAILED\") { return \"status-failed\"; }\n");
      out.write("        if (status === \"PARTIAL\") { return \"status-partial\"; }\n");
      out.write("        if (status === \"RUNNING\") { return \"status-running\"; }\n");
      out.write("        return \"status-unknown\";\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function nowText() {\n");
      out.write("        var d = new Date();\n");
      out.write("        var yyyy = d.getFullYear();\n");
      out.write("        var mm = (\"0\" + (d.getMonth() + 1)).slice(-2);\n");
      out.write("        var dd = (\"0\" + d.getDate()).slice(-2);\n");
      out.write("        var hh = (\"0\" + d.getHours()).slice(-2);\n");
      out.write("        var mi = (\"0\" + d.getMinutes()).slice(-2);\n");
      out.write("        var ss = (\"0\" + d.getSeconds()).slice(-2);\n");
      out.write("        return yyyy + \"-\" + mm + \"-\" + dd + \" \" + hh + \":\" + mi + \":\" + ss;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function buildSummary(rows, days, pn, pageSize, totalRecords, totalPages) {\n");
      out.write("        var successDays = 0;\n");
      out.write("        var failedDays = 0;\n");
      out.write("        var runningDays = 0;\n");
      out.write("\n");
      out.write("        $.each(rows || [], function(i, row) {\n");
      out.write("            var status = row && row.dailyStatus ? row.dailyStatus : \"UNKNOWN\";\n");
      out.write("            if (status === \"SUCCESS\") { successDays++; }\n");
      out.write("            if (status === \"FAILED\") { failedDays++; }\n");
      out.write("            if (status === \"RUNNING\") { runningDays++; }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $(\"#summary_area\").text(\n");
      out.write("            \"Review Window: \" + days + \" days\"\n");
      out.write("            + \" | Days with runs: \" + toInt(totalRecords)\n");
      out.write("            + \" | Page: \" + pn + \"/\" + (totalPages <= 0 ? 1 : totalPages)\n");
      out.write("            + \" | Page Size: \" + pageSize\n");
      out.write("            + \" | Success (this page): \" + successDays\n");
      out.write("            + \" | Failed (this page): \" + failedDays\n");
      out.write("            + \" | Running (this page): \" + runningDays\n");
      out.write("        );\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function buildTable(rows, pn, pageSize) {\n");
      out.write("        var tbody = $(\"#scheduler_table tbody\");\n");
      out.write("        tbody.empty();\n");
      out.write("        if (!rows || rows.length === 0) {\n");
      out.write("            $(\"<tr></tr>\")\n");
      out.write("                .append($(\"<td></td>\").attr(\"colspan\", 11).text(\"No scheduler status records found.\"))\n");
      out.write("                .appendTo(tbody);\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        $.each(rows, function(index, item) {\n");
      out.write("            var status = item && item.dailyStatus ? item.dailyStatus : \"UNKNOWN\";\n");
      out.write("            var serial = ((pn - 1) * pageSize) + index + 1;\n");
      out.write("            var badge = $(\"<span></span>\")\n");
      out.write("                .addClass(\"status-pill\")\n");
      out.write("                .addClass(statusClass(status))\n");
      out.write("                .text(status);\n");
      out.write("            $(\"<tr></tr>\")\n");
      out.write("                .append($(\"<td></td>\").text(serial))\n");
      out.write("                .append($(\"<td></td>\").text(safeText(item.runDate)))\n");
      out.write("                .append($(\"<td></td>\").append(badge))\n");
      out.write("                .append($(\"<td></td>\").text(toInt(item.runCount)))\n");
      out.write("                .append($(\"<td></td>\").text(toInt(item.successCount)))\n");
      out.write("                .append($(\"<td></td>\").text(toInt(item.failedCount)))\n");
      out.write("                .append($(\"<td></td>\").text(safeText(item.firstStartedAt)))\n");
      out.write("                .append($(\"<td></td>\").text(safeText(item.lastFinishedAt)))\n");
      out.write("                .append($(\"<td></td>\").text(toInt(item.enabledUsers)))\n");
      out.write("                .append($(\"<td></td>\").text(toInt(item.disabledUsers)))\n");
      out.write("                .append($(\"<td></td>\").text(toInt(item.deletedUsers)))\n");
      out.write("                .appendTo(tbody);\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function buildPagination(pn, totalPages, totalRecords) {\n");
      out.write("        var area = $(\"#pagination_area\");\n");
      out.write("        area.empty();\n");
      out.write("\n");
      out.write("        if (!totalRecords || totalRecords <= 0) {\n");
      out.write("            area.text(\"No pages\");\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        var prevBtn = $(\"<button></button>\")\n");
      out.write("            .addClass(\"btn btn-default btn-sm\")\n");
      out.write("            .text(\"Prev\")\n");
      out.write("            .prop(\"disabled\", pn <= 1);\n");
      out.write("        var nextBtn = $(\"<button></button>\")\n");
      out.write("            .addClass(\"btn btn-default btn-sm\")\n");
      out.write("            .css(\"margin-left\", \"8px\")\n");
      out.write("            .text(\"Next\")\n");
      out.write("            .prop(\"disabled\", pn >= totalPages);\n");
      out.write("        var info = $(\"<span></span>\")\n");
      out.write("            .css(\"margin-left\", \"10px\")\n");
      out.write("            .text(\"Page \" + pn + \" of \" + totalPages + \" | Total Days: \" + totalRecords);\n");
      out.write("\n");
      out.write("        prevBtn.click(function() {\n");
      out.write("            if (pn > 1) {\n");
      out.write("                loadSchedulerStatus(pn - 1);\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("        nextBtn.click(function() {\n");
      out.write("            if (pn < totalPages) {\n");
      out.write("                loadSchedulerStatus(pn + 1);\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        area.append(prevBtn).append(nextBtn).append(info);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function renderDbSyncSummary(ext) {\n");
      out.write("        ext = ext || {};\n");
      out.write("        var running = ext.running === true;\n");
      out.write("        var state = safeUpper(ext.state || \"\");\n");
      out.write("        if (state === \"\") {\n");
      out.write("            state = running ? \"RUNNING\" : \"IDLE\";\n");
      out.write("        }\n");
      out.write("        var msg = \"state=\" + state\n");
      out.write("            + \" | users=\" + toInt(ext.activeUsers)\n");
      out.write("            + \" | enrollRecords=\" + toInt(ext.totalEnrollRecords)\n");
      out.write("            + \" | queued=\" + toInt(ext.totalCommandsQueued)\n");
      out.write("            + \" (setuserinfo=\" + toInt(ext.setuserinfoCommandsQueued)\n");
      out.write("            + \", cleanadmin=\" + toInt(ext.cleanAdminCommandsQueued) + \")\"\n");
      out.write("            + \" | devices=\" + toInt(ext.devices)\n");
      out.write("            + \" | onlineDevices=\" + toInt(ext.onlineDevices)\n");
      out.write("            + \" | eta=\" + toInt(ext.estimatedDeviceDispatchSeconds) + \" sec\";\n");
      out.write("        var detailMessage = $.trim(ext.message || \"\");\n");
      out.write("        if (detailMessage !== \"\") {\n");
      out.write("            msg += \" | note=\" + safeMessage(detailMessage);\n");
      out.write("        }\n");
      out.write("        $(\"#db_sync_summary\").text(msg);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function mergeDbSyncRows(deviceDetails, deviceSyncStateRows) {\n");
      out.write("        var runtimeDetails = $.isArray(deviceDetails) ? deviceDetails : [];\n");
      out.write("        var stateRows = $.isArray(deviceSyncStateRows) ? deviceSyncStateRows : [];\n");
      out.write("        var runtimeBySerial = {};\n");
      out.write("        $.each(runtimeDetails, function(index, detail) {\n");
      out.write("            if (!detail) { return; }\n");
      out.write("            var serial = $.trim(detail.serial || \"\");\n");
      out.write("            if (serial === \"\") { return; }\n");
      out.write("            runtimeBySerial[serial.toUpperCase()] = detail;\n");
      out.write("        });\n");
      out.write("        var merged = [];\n");
      out.write("        $.each(stateRows, function(index, row) {\n");
      out.write("            if (!row) { return; }\n");
      out.write("            var serial = $.trim(row.serial || \"\");\n");
      out.write("            if (serial === \"\") { return; }\n");
      out.write("            var key = serial.toUpperCase();\n");
      out.write("            merged.push({\n");
      out.write("                serial: serial,\n");
      out.write("                state: row,\n");
      out.write("                runtime: runtimeBySerial[key] || null\n");
      out.write("            });\n");
      out.write("            delete runtimeBySerial[key];\n");
      out.write("        });\n");
      out.write("        $.each(runtimeBySerial, function(serialKey, detail) {\n");
      out.write("            if (!detail) { return; }\n");
      out.write("            merged.push({\n");
      out.write("                serial: $.trim(detail.serial || serialKey),\n");
      out.write("                state: null,\n");
      out.write("                runtime: detail\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("        return merged;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function renderDbSyncDeviceTable(deviceDetails, deviceSyncStateRows) {\n");
      out.write("        var tbody = $(\"#db_sync_device_table tbody\");\n");
      out.write("        tbody.empty();\n");
      out.write("            var mergedRows = mergeDbSyncRows(deviceDetails, deviceSyncStateRows);\n");
      out.write("            if (!mergedRows.length) {\n");
      out.write("                $(\"<tr></tr>\")\n");
      out.write("                    .append($(\"<td></td>\").attr(\"colspan\", 12).text(\"No per-device sync status available.\"))\n");
      out.write("                    .appendTo(tbody);\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("        $.each(mergedRows, function(index, row) {\n");
      out.write("            var state = row.state || {};\n");
      out.write("            var runtime = row.runtime || {};\n");
      out.write("            var serial = $.trim(row.serial || runtime.serial || state.serial || \"\");\n");
      out.write("            if (serial === \"\") { serial = \"device-\" + (index + 1); }\n");
      out.write("            var stateOnline = state.online;\n");
      out.write("            var runtimeOnline = runtime.online;\n");
      out.write("            var online = (stateOnline === true || runtimeOnline === true || toInt(stateOnline) === 1 || toInt(runtimeOnline) === 1) ? \"Yes\" : \"No\";\n");
      out.write("            var lastStatus = safeUpper(state.lastSyncStatus || runtime.syncStatus || \"NEVER\");\n");
      out.write("            var lastSyncAt = safeText(state.lastSyncAt || runtime.lastSyncAt || \"\");\n");
      out.write("            var lastQueued = toInt(state.lastQueuedSetuserinfo, toInt(runtime.queuedSetuserinfo));\n");
      out.write("            var delivered = toInt(state.deliveredSetuserinfoCount);\n");
      out.write("            var pending = (runtime.pendingAfter === undefined || runtime.pendingAfter === null || runtime.pendingAfter === \"\") ? \"-\" : toInt(runtime.pendingAfter);\n");
      out.write("            var queuedUsers = (runtime.deltaUserCount === undefined || runtime.deltaUserCount === null || runtime.deltaUserCount === \"\") ? \"-\" : toInt(runtime.deltaUserCount);\n");
      out.write("            var queuedThisRun = (runtime.queuedSetuserinfo === undefined || runtime.queuedSetuserinfo === null || runtime.queuedSetuserinfo === \"\") ? \"-\" : toInt(runtime.queuedSetuserinfo);\n");
      out.write("            var etaSec = (runtime.estimatedDispatchSeconds === undefined || runtime.estimatedDispatchSeconds === null || runtime.estimatedDispatchSeconds === \"\") ? \"-\" : toInt(runtime.estimatedDispatchSeconds);\n");
      out.write("            var message = safeMessage(runtime.syncMessage || state.lastErrorMessage || state.lastSyncMessage || \"\");\n");
      out.write("            $(\"<tr></tr>\")\n");
      out.write("                .append($(\"<td></td>\").text(index + 1))\n");
      out.write("                .append($(\"<td></td>\").text(serial))\n");
      out.write("                .append($(\"<td></td>\").text(online))\n");
      out.write("                .append($(\"<td></td>\").text(lastStatus))\n");
      out.write("                .append($(\"<td></td>\").text(lastSyncAt))\n");
      out.write("                .append($(\"<td></td>\").text(lastQueued))\n");
      out.write("                .append($(\"<td></td>\").text(delivered))\n");
      out.write("                .append($(\"<td></td>\").text(pending))\n");
      out.write("                .append($(\"<td></td>\").text(queuedUsers))\n");
      out.write("                .append($(\"<td></td>\").text(queuedThisRun))\n");
      out.write("                .append($(\"<td></td>\").text(etaSec))\n");
      out.write("                .append($(\"<td></td>\").text(message))\n");
      out.write("                .appendTo(tbody);\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function loadDbSyncStatus(updateStatusMsg) {\n");
      out.write("        var shouldUpdateStatusMsg = (updateStatusMsg !== false);\n");
      out.write("        if (shouldUpdateStatusMsg) {\n");
      out.write("            $(\"#status_msg\").text(\"Loading...\");\n");
      out.write("        }\n");
      out.write("        $.ajax({\n");
      out.write("            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/setUserToAllDeviceStatus\",\n");
      out.write("            type: \"GET\",\n");
      out.write("            cache: false,\n");
      out.write("            success: function(result) {\n");
      out.write("                if (!result || result.code !== 100) {\n");
      out.write("                    var err = result && result.extend && result.extend.error ? result.extend.error : \"Unable to load SetUserToAllDevice status.\";\n");
      out.write("                    $(\"#db_sync_summary\").text(err);\n");
      out.write("                    renderDbSyncDeviceTable([], []);\n");
      out.write("                    if (shouldUpdateStatusMsg) {\n");
      out.write("                        $(\"#status_msg\").text(err);\n");
      out.write("                    }\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                var ext = result.extend || {};\n");
      out.write("                renderDbSyncSummary(ext);\n");
      out.write("                renderDbSyncDeviceTable(ext.deviceDetails, ext.deviceSyncStateRows);\n");
      out.write("                if (shouldUpdateStatusMsg) {\n");
      out.write("                    $(\"#status_msg\").text(\"Last refreshed: \" + nowText());\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            error: function() {\n");
      out.write("                $(\"#db_sync_summary\").text(\"Load failed: SetUserToAllDevice status\");\n");
      out.write("                renderDbSyncDeviceTable([], []);\n");
      out.write("                if (shouldUpdateStatusMsg) {\n");
      out.write("                    $(\"#status_msg\").text(\"Load failed\");\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function loadSchedulerStatus(pageToLoad) {\n");
      out.write("        var days = toInt($(\"#days_select\").val());\n");
      out.write("        var pageSize = toInt($(\"#page_size_select\").val());\n");
      out.write("        if (days <= 0) {\n");
      out.write("            days = 30;\n");
      out.write("        }\n");
      out.write("        if (pageSize <= 0) {\n");
      out.write("            pageSize = 10;\n");
      out.write("        }\n");
      out.write("        var targetPage = toInt(pageToLoad);\n");
      out.write("        if (targetPage <= 0) {\n");
      out.write("            targetPage = currentPage <= 0 ? 1 : currentPage;\n");
      out.write("        }\n");
      out.write("        $(\"#status_msg\").text(\"Loading...\");\n");
      out.write("        $.ajax({\n");
      out.write("            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schedulerDailyStatus\",\n");
      out.write("            type: \"GET\",\n");
      out.write("            data: { days: days, pn: targetPage, pageSize: pageSize },\n");
      out.write("            cache: false,\n");
      out.write("            success: function(result) {\n");
      out.write("                if (!result || result.code !== 100) {\n");
      out.write("                    var err = result && result.extend && result.extend.error ? result.extend.error : \"Unable to load scheduler status.\";\n");
      out.write("                    $(\"#status_msg\").text(err);\n");
      out.write("                    buildTable([], 1, pageSize);\n");
      out.write("                    buildSummary([], days, 1, pageSize, 0, 0);\n");
      out.write("                    buildPagination(1, 0, 0);\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                var ext = result.extend || {};\n");
      out.write("                var rows = ext.rows || [];\n");
      out.write("                var pn = toInt(ext.pn);\n");
      out.write("                var totalPages = toInt(ext.totalPages);\n");
      out.write("                var totalRecords = toInt(ext.totalRecords);\n");
      out.write("                var effectivePageSize = toInt(ext.pageSize);\n");
      out.write("                var effectiveDays = toInt(ext.days);\n");
      out.write("                if (pn <= 0) { pn = 1; }\n");
      out.write("                if (totalPages < 0) { totalPages = 0; }\n");
      out.write("                if (effectivePageSize <= 0) { effectivePageSize = pageSize; }\n");
      out.write("                if (effectiveDays <= 0) { effectiveDays = days; }\n");
      out.write("                currentPage = pn;\n");
      out.write("                buildTable(rows, pn, effectivePageSize);\n");
      out.write("                buildSummary(rows, effectiveDays, pn, effectivePageSize, totalRecords, totalPages);\n");
      out.write("                buildPagination(pn, totalPages, totalRecords);\n");
      out.write("                $(\"#status_msg\").text(\"Last refreshed: \" + nowText());\n");
      out.write("                schedulerLoadedOnce = true;\n");
      out.write("            },\n");
      out.write("            error: function() {\n");
      out.write("                $(\"#status_msg\").text(\"Load failed\");\n");
      out.write("                buildTable([], 1, pageSize);\n");
      out.write("                buildSummary([], days, 1, pageSize, 0, 0);\n");
      out.write("                buildPagination(1, 0, 0);\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function setStatusView(viewName, forceReload) {\n");
      out.write("        var isScheduled = (viewName === \"scheduled\");\n");
      out.write("        currentView = isScheduled ? \"scheduled\" : \"perDevice\";\n");
      out.write("\n");
      out.write("        $(\"#view_per_device\").toggleClass(\"active\", !isScheduled);\n");
      out.write("        $(\"#view_scheduled\").toggleClass(\"active\", isScheduled);\n");
      out.write("\n");
      out.write("        $(\"#show_per_device_btn\")\n");
      out.write("            .toggleClass(\"btn-info\", !isScheduled)\n");
      out.write("            .toggleClass(\"btn-default\", isScheduled);\n");
      out.write("        $(\"#show_scheduled_btn\")\n");
      out.write("            .toggleClass(\"btn-info\", isScheduled)\n");
      out.write("            .toggleClass(\"btn-default\", !isScheduled);\n");
      out.write("\n");
      out.write("        if (isScheduled) {\n");
      out.write("            if (forceReload || !schedulerLoadedOnce) {\n");
      out.write("                loadSchedulerStatus(currentPage <= 0 ? 1 : currentPage);\n");
      out.write("            } else {\n");
      out.write("                $(\"#status_msg\").text(\"Showing Scheduled Status\");\n");
      out.write("            }\n");
      out.write("        } else if (forceReload) {\n");
      out.write("            loadDbSyncStatus(true);\n");
      out.write("        } else {\n");
      out.write("            $(\"#status_msg\").text(\"Showing Per Device Status\");\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    $(\"#refresh_btn\").click(function() {\n");
      out.write("        if (currentView === \"scheduled\") {\n");
      out.write("            loadSchedulerStatus(currentPage);\n");
      out.write("        } else {\n");
      out.write("            loadDbSyncStatus(true);\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\"#days_select\").change(function() {\n");
      out.write("        currentPage = 1;\n");
      out.write("        loadSchedulerStatus(1);\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\"#page_size_select\").change(function() {\n");
      out.write("        currentPage = 1;\n");
      out.write("        loadSchedulerStatus(1);\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\"#back_btn\").click(function() {\n");
      out.write("        window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\";\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\"#show_per_device_btn\").click(function() {\n");
      out.write("        setStatusView(\"perDevice\", true);\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\"#show_scheduled_btn\").click(function() {\n");
      out.write("        setStatusView(\"scheduled\", true);\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(function() {\n");
      out.write("        setStatusView(\"perDevice\", false);\n");
      out.write("        loadDbSyncStatus(true);\n");
      out.write("        setInterval(function() {\n");
      out.write("            if (currentView === \"perDevice\") {\n");
      out.write("                loadDbSyncStatus(false);\n");
      out.write("            }\n");
      out.write("        }, 5000);\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
